// Copyright (c) 2012 The LevelDB Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file. See the AUTHORS file for names of contributors.

#include "leveldb/filter_policy.h"

#include "leveldb/slice.h"
#include "util/hash.h"
#include <db/dbformat.h>
#include<stdio.h>
#include<stdlib.h>
namespace leveldb {

namespace {
static uint32_t BloomHash(const Slice& key) {
  return Hash(key.data(), key.size(), 0xbc9f1d34);
}
static size_t bits[] = {31,30,27,28,18,1,1};
class BloomFilterPolicy : public FilterPolicy {
 private:
  size_t bits_per_key_[config::kNumLevels];
  size_t k_[config::kNumLevels];
  
 public:
  explicit BloomFilterPolicy(const char *filename){
    // We intentionally round down to reduce probing cost a little bit
    FILE *fp = fopen(filename,"r");
    unsigned int j = 0 ;
    while(fscanf(fp,"%lu",&bits[j++])!=EOF);
    while( j < 7){
 	bits[j++] = 1;
     }
    for(unsigned int i = 0 ; i < config::kNumLevels ; i++){
      bits_per_key_[i] = bits[i];
      k_[i]= static_cast<size_t>(bits_per_key_[i] * 0.69);  // 0.69 =~ ln(2)
    
      if (k_[i] < 1) k_[i] = 1;
      if (k_[i] > 30) k_[i] = 30;
    }
    printf("\n");
    for(unsigned int i = 0 ; i < config::kNumLevels ; i++){
 	 printf("%d:%lu ",i,bits_per_key_[i]);
     }
     printf("\n");
  }

  virtual const char* Name() const {
    return "leveldb.DynamicBloomFilter";
  }

  virtual void CreateFilter(const Slice* keys, int n, std::string* dst,int level) const {
    // Compute bloom filter size (in both bits and bytes)
    size_t bits = n * bits_per_key_[level];
    if(level >= 7){
      printf("level%d:%lu ",level,bits_per_key_[level]);
    }
    // For small n, we can see a very high false positive rate.  Fix it
    // by enforcing a minimum bloom filter length.
    if (bits < 64) bits = 64;

    size_t bytes = (bits + 7) / 8;
    bits = bytes * 8;

    const size_t init_size = dst->size();
    dst->resize(init_size + bytes, 0);
    dst->push_back(static_cast<char>(k_[level]));  // Remember # of probes in filter
    char* array = &(*dst)[init_size];
    for (int i = 0; i < n; i++) {
      // Use double-hashing to generate a sequence of hash values.
      // See analysis in [Kirsch,Mitzenmacher 2006].
      uint32_t h = BloomHash(keys[i]);
      const uint32_t delta = (h >> 17) | (h << 15);  // Rotate right 17 bits
      for (size_t j = 0; j < k_[level]; j++) {
        const uint32_t bitpos = h % bits;
        array[bitpos/8] |= (1 << (bitpos % 8));
        h += delta;
      }
    }
  }

  virtual bool KeyMayMatch(const Slice& key, const Slice& bloom_filter) const {
    const size_t len = bloom_filter.size();
    if (len < 2) return false;

    const char* array = bloom_filter.data();
    const size_t bits = (len - 1) * 8;

    // Use the encoded k so that we can read filters generated by
    // bloom filters created using different parameters.
    const size_t k = array[len-1];
    if (k > 30) {
      // Reserved for potentially new encodings for short bloom filters.
      // Consider it a match.
      return true;
    }

    uint32_t h = BloomHash(key);
    const uint32_t delta = (h >> 17) | (h << 15);  // Rotate right 17 bits
    for (size_t j = 0; j < k; j++) {
      const uint32_t bitpos = h % bits;
      if ((array[bitpos/8] & (1 << (bitpos % 8))) == 0) return false;
      h += delta;
    }
    return true;
  }
};
}

const FilterPolicy* NewBloomFilterPolicy(void *strFilename) {
    char *filename = static_cast<char*>(strFilename);
   return new BloomFilterPolicy(filename);
 // return new BloomFilterPolicy(bits_per_key);
}

}  // namespace leveldb
